#mysql service
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  type: ClusterIP
  selector:
    app: spring-website
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: spring-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mysql
  template:
    metadata:
      labels:
        app: spring-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.8
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_DATABASE"
          value: "petclinic"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-website
  template:
    metadata:
      labels:
        app: spring-website
    spec:
      containers:
      - name: spring-website
        image: shadifadila/my_repo:spring
        ports:
        - containerPort: 8080