apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  type: NodePort
  selector:
    app: spring-website
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-website
  template:
    metadata:
      labels:
        app: spring-website
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: petclinic
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: petclinic
        - name: MYSQL_PASSWORD
          value: petclinic
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
      - name: spring-website
        image: shadifadila/my_repo:spring
        ports:
        - containerPort: 8080