apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-website
  template:
    metadata:
      labels:
        app: spring-website
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: MYSQL_DATABASE
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: MYSQL_DATABASE
      - name: spring-website
        image: shadifadila/my_repo:spring
        ports:
        - containerPort: 8080