apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars
data:
  MYSQL_DATABASE1: petclinic
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: petclinic
  MYSQL_PASSWORD: petclinic
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"